import Head from 'next/head'
import dynamic from 'next/dynamic';

//import components
import Header from '../components/header.component';
import Caroussell from '../components/carousell.component';

const ProductDiscover = dynamic(() => import('../components/home/product-discover.component'));
const ProductDisplay = dynamic(() => import('../components/home/product-display.component'));
const ProductHorizontalDiscover = dynamic(() => import('../components/home/product-horizontal-discover.component'));
const Footer = dynamic(() => import('../components/footer.component'));

import CookiesService from '../services/cookies.service';

export default function Home() {
    return (
        <>

            <Head>
                <title>LEUTI.ID | Leuti Perfect Sublimate Serum</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon-leuti.ico" />
            </Head>

            <Header />

            <main className=' md:w-4/5 flex flex-col space-y-9 m-auto'>

                {/* carousell */}
                <div className='md:w-full md:h-[650px] w-full h-screen flex justify-center md:my-10 bg-white md:bg-gray-100'>
                    <Caroussell />
                </div>
                {/* end carousell */}

                <ProductDiscover />
                <ProductDisplay />
                <ProductHorizontalDiscover />

            </main>

            <Footer />
        </>
    )
}

export async function getServerSideProps(context) {

    const { req, res } = context;
    let isLogin = false;
    let user = {};

    try {

        const cookies = await CookiesService.getCookies('user', req, res);

        if (cookies) {

            const cookiesParsed = JSON.parse(cookies);

            if (cookiesParsed.accessToken) {
                user = cookiesParsed;
                isLogin = true;
            }
        }

    } catch (error) {

        if (error) {
            isLogin = false;
        }
    }

    return {
        props: {
            isLogin,
            user,
        }
    }
}