import Head from 'next/head'
import dynamic from 'next/dynamic';
import styles from '../styles/Home.module.css'

//import components
import Header from '../components/header.component';
import Footer from '../components/footer.component';
import Caroussell from '../components/carousell.component';
// import ProductDiscover from '../components/home/product-discover.component';

const ProductDiscover = dynamic(() => import('../components/home/product-discover.component'));

export default function Home() {

  return (
    <div className={styles.container}>

      <Head>
        <title>Leuti Perfect Sublimate Serum - LEUTI.ID</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className=' md:w-4/5 m-auto'>

        {/* carousell */}
        <div className='md:w-full md:h-[650px] md:flex md:justify-center md:mt-10'>
          <Caroussell />
        </div>
        {/* end carousell */}

        <ProductDiscover />
      </main>

      <Footer />
    </div>
  )
}
